config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }

  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :answers, only: %i[show destroy]
    resources :users, only: %i[show update]
    resources :counselings, only: %i[show destroy]
  end

  namespace :user do
    get 'counselings/search' => 'counselings#search'
    resources :counselings, only: %i[create destroy edit new show update] do
      resources :answers, only: %i[create destroy]
    end
    resources :admins, only: [:index]
    resources :customers, only: %i[show edit update]
    get 'customers/:id/confirm' => 'customers#confirm', as: 'confirm'
    patch 'customer/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    post 'good/:id' => 'goods#create', as: 'create_good'
    delete 'good/:id' => 'goods#destroy', as: 'destroy_good'
    post 'not_good/:id' => 'not_goods#create', as: 'create_not_good'
    delete 'not_good/:id' => 'not_goods#destroy', as: 'destroy_not_good'
  end
  root to: 'user/homes#index'
  resources :contacts, only: %i[new create]
  get 'contacts/thanks' => 'contacts#thanks', as: 'thanks'
end

app/models/counseling.rb
class Counseling < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :answers, dependent: :destroy
  validates :level, presence: true, numericality: { greater_than_or_equal_to: 1, less_than: 6 }
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def good_by?(answer_id)
    goods.where(answer_id: answer_id).exists?
  end
  def not_good_by?(answer_id)
    not_goods.where(answer_id: answer_id).exists?
  end

  has_many :contacts, dependent: :destroy
  has_many :counselings, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :goods, dependent: :destroy
  has_many :not_goods, dependent: :destroy

end

app/controllers/admin/counselings_controller.rb
class Admin::CounselingsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @counseling = Counseling.find(params[:id])
  end

  def destroy
    @counseling = Counseling.find(params[:id])
    @counseling.destroy
    redirect_to admin_root_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @counselings = @user.counselings.reverse_order
    @answers = @user.answers.reverse_order
  end

  def update
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    redirect_to admin_root_path
  end
end

app/controllers/user/admins_controller.rb
class User::AdminsController < ApplicationController
end

app/controllers/user/answers_controller.rb
class User::AnswersController < ApplicationController
  def create
    @counseling = Counseling.find(params[:counseling_id])
    @answer = current_user.answers.new(answer_params)
    @answer.counseling_id = @counseling.id
    if @answer.save
      redirect_to user_counseling_path(@answer.counseling.id)
    else
      render 'user/counselings/show'
    end
  end

  def destroy
    Answer.find_by(id: params[:id]).destroy
    redirect_to user_counseling_path(params[:counseling_id])
  end

  private

  def answer_params
    params.require(:answer).permit(:content).merge(user_id: current_user.id, counseling_id: params[:counseling_id])
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/counselings_controller.rb
class User::CounselingsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :correct_counseling, only: [:edit]

  def new
    @counseling = Counseling.new
    @genres = Genre.all
  end

  def create
    @counseling = Counseling.new(counseling_params)
    @genres = Genre.all
    @counseling.genre_id = params[:genre][:name]
    @counseling.user_id = current_user.id
    if @counseling.save
      flash[:notic] = '投稿に成功しました！回答が来るのを待ちましょう。'
      redirect_to user_counseling_path(@counseling)
    else
      render 'user/counselings/new.html.erb'
    end
  end

  def show
    @counseling = Counseling.find(params[:id])
    @answer = Answer.new
    @user = @counseling.user
  end

  def edit
    @counseling = Counseling.find(params[:id])
    @genres = Genre.all
  end

  def update
    @counseling = Counseling.find(params[:id])
    @counseling.genre_id = params[:genre][:name]
    @counseling.update(counseling_params)
    redirect_to user_counseling_path(@counseling)
  end

  def destroy
    @counseling = Counseling.find(params[:id])
    @counseling.destroy
    redirect_to user_customer_path(current_user)
  end

  def search
    @counseling = Counseling.all
    @count = @search_counseling.count
  end

  private

  def counseling_params
    params.require(:counseling).permit(:user_id, :genre, :title, :content, :level)
  end

  def correct_counseling
    @counseling = Counseling.find(params[:id])
    redirect_to root_path unless @counseling.user.id == current_user.id
  end
end

app/controllers/user/customers_controller.rb
class User::CustomersController < ApplicationController
  before_action :correct_user, only: [:show, :edit, :confirm]

  def show
    @user = User.find(params[:id])
    @counselings = current_user.counselings.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_customer_path(@user.id)
  end

  def confirm
    @user = User.find(params[:id])
  end

  def unsubscribe
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notic] = 'またお悩みがあればいつでもお待ちしております。ご利用ありがとうございました。'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :self_introduction, :club, :email)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless @user.id == current_user.id
  end
end

app/controllers/user/goods_controller.rb
class User::GoodsController < ApplicationController
  def create
    Good.create(user_id: current_user.id, answer_id: params[:id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    Good.find_by(user_id: current_user.id, answer_id: params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def index
    @counselings = Counseling.all.order(created_at: :desc).page(params[:page]).per(5)
    @count = Counseling.count
  end
end

app/controllers/user/not_goods_controller.rb
class User::NotGoodsController < ApplicationController
  def create
    NotGood.create(user_id: current_user.id, answer_id: params[:id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    NotGood.find_by(user_id: current_user.id, answer_id: params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name image club self_introduction])
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = '退会済みです。新規登録から再度登録して下さい。'
        redirect_to new_user_registration_path
      end
    else
      flash[:error] = '必須項目を入力してください。'
    end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/counselings_helper.rb
module Admin::CounselingsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/counselings_helper.rb
module CounselingsHelper
end

app/views/user/counselings/edit.html.erb
<div class="text-center">
 <div class="title mt-3">
  相談を編集する
 </div>
  <%= form_with model:@counseling, url: user_counseling_path,local:true do |f| %>
   <%= f.label :title,"相談タイトル" %><br>
     <p><%= f.text_field :title ,size:"50x3"%></p>
    相談のジャンル<br>
     <p><%= collection_select(:genre, :name, @genres, :id, :genre) %></p>
     <%= f.label :level,"辛さのレベル" %>(1~5で選択して下さい。)<br>
    <p><%= f.number_field :level, in: 1..5 %></p>
     <%= f.label :content,"相談内容" %><br>
    <p><%= f.text_area :content, size: "40x10" %></p>
   <p><%= f.submit'相談を編集する',class:"btn btn-success" %></p>
  <% end %>
</div>
</div>

app/views/user/counselings/new.html.erb
<div class="text-center">
 <div class="title mt-3">
  相談を投稿する
 </div>
  <% if @counseling.errors.any? %>
   <div class = "alert">
    <ul>
      <% @counseling.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
 <% end %>
<div class="text-center">
 <%= form_with model:@counseling, url: user_counselings_path,local:true do |f| %>
   <%= f.label :title,"相談タイトル" %><br>
   <p><%= f.text_field :title %></p>
   相談のジャンル<br>
   <p><%= collection_select(:genre, :name, @genres, :id, :genre) %></p>
   <%= f.label :level,"辛さのレベル" %>(1~5で選択して下さい。)<br>
   <p><%= f.number_field :level, in: 1..5 %></p>
   <%= f.label :content,"相談内容" %><br>
   <p><%= f.text_area :content, size: "40x10"%></p>
   <p><%= f.submit'相談を投稿する',class:"btn btn-success" %></p>
  <% end %>
 </div>
</div>

app/views/user/counselings/search.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-10 offset-1">
   <div class="text-center">
    <div class="title mt-3">
     <%= @count %>件の相談が見つかりました!
    </div>
    <% @search_counseling.each do |counseling| %>
     <table class= table mt-3 style="table-layout:fixed;width:100%;">
      <thead>
       <tr class="border-bottom" style="word-wrap:break-word;">
        <th>
        <%= link_to user_counseling_path(counseling) do %>
        <p><%= counseling.title %></p>
       <% end %>
      相談のジャンル&nbsp;
       <%= counseling.genre.genre %>
       </th>
      </tr>
     </thead>
    <% end %>
   </table>
  </div>
 </div>
</div>

app/views/user/counselings/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-10 offset-2"> <% if @answer.errors.any? %>
   <div class = "alert">
    <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= flash[:notic] %>
<div class="title mt-4">
  <div class="title" style="word-wrap:break-word;">
   <div class="col">
    <%= @counseling.title %>
    </div>
   </div>
  </div>
 </div>
<div class="col-md-2 offset-2 ">
 <%= attachment_image_tag @user, :image, :fill, 120, 120, format: 'jpeg', class:"exmaple-hoge", fallback: "no_image.jpg", size:"180x180" %><br>
</div>
 <div class="col-md-2 mt-3">
  <h5>相談者</h5>
  <h5>部活</h5>
  <h5>辛さレベル(1~5)</h5>
  <h5>ジャンル</h5>
  <h5>自己紹介</h5>
 </div>
 <div class="col-md-4 mt-3">
   <h5><%= @counseling.user.name %></h5>
   <h5><%= @counseling.user.club %></h5>
   <h5><%= @counseling.level %></h5>
   <h5><%= @counseling.genre.genre %></h5>
  <div class="text" style="word-wrap:break-word;">
   <h5><%= @counseling.user.self_introduction %></h5>
  </div>
 </div>
  <br>
 <div class="col-md-10 offset-2">
   <h5>相談内容</h5>
     <div class="text" style="word-wrap:break-word;">
      <h5>
       <%= @counseling.content %>
     </h5>
    </div>
    <% if @counseling.user == current_user %>
     <div>
      <%= link_to "削除する", user_counseling_path(@counseling), method: :delete, data: {confirm: "相談を削除してよろしいですか？"},class:"btn btn-danger" %>
      <%= link_to "編集する", edit_user_counseling_path(@counseling),class:"btn btn-success" %><br><br>
     </div>
    <% end %>
    <div class="border-bottom">
     <%= form_with(model:[@counseling, @answer],url:user_counseling_answers_path(@counseling), local: true) do |f| %>
      <p><%= f.text_area :content, rows:'5',placeholder: "この相談に回答する", size: "80x3" %></p>
      <%= f.submit "送信する",class:"btn btn-success" %>
      <p>(回答によくないねが5個以上つくと削除される場合があります。)</p>
     <% end %>
     <h4 class="mt-2">合計<%= @counseling.answers.count %>件の回答が届いています。</h4>
     </div>
     <% @counseling.answers.each do |answer| %>
      <table class= table style="table-layout:fixed;width:100%;">
       <thead>
       <tr class="border-bottom" style="word-wrap:break-word;">
        <th>
         <p class="text mt-2"><%= answer.content %></p>
          <% if current_user.good_by?(answer.id) %>
           <%= link_to 'いいねを外す', user_destroy_good_path(answer), method: :DELETE %>
           <%= answer.goods.count %>個のいいねがついています!
          <% else %>
           <%= link_to '回答にいいねする', user_create_good_path(answer), method: :POST %>
           <%= answer.goods.count %>個のいいねがついています!
          <% end %>
          <% if current_user.not_good_by?(answer.id) %>
           <p><%= link_to 'よくないねを外す', user_destroy_not_good_path(answer), method: :DELETE %>
           <%= answer.not_goods.count %>個のよくないねがついています</p>
          <% else %>
           <p><%= link_to '回答によくないねする', user_create_not_good_path(answer), method: :POST %>
           <%= answer.not_goods.count %>個のよくないねがついています</p>
          <% end %>
          <% if answer.user == current_user %>
         <div>
          <%= link_to "削除", user_counseling_answer_path(answer.counseling_id, answer), method: :delete, data: {confirm: "回答を削除してよろしいですか？"},class:"btn btn-danger" %>
         </div>
        <% end %>
       </th>
      </tr>
     </thead>
    <% end %>
   </table>
  </div>
 </div>
</div>